# This file is used to generate the file `config.gen.go`; we compile these phrases into the binary
# (rather than allowing for a separate runtime configuration options) purely because it makes
# distribution and start up a little easier for us.
#
# The only reason to have this seperate file, rather than storing this in source, is so these
# things can be edited and maintained by people who feel less confident editing source code.

[responses]
# Greeting Response is sent when a recipient sends a message that looks vaguely like
# a greeting.
#
# To understand what this might look like, take a look in phrases.go
greeting = "Hello, and welcome to the Anonymous GEC Advisor. What's on your mind?"

# Thank You response is sent when a recipient sends us a message.
#
# To keep this from spamming the hell out of people, we only send a maximum of 1
# response per 30 minutes.
#
# Essentially, when  a message comes in, we check whether we've responded in the last
# 30 minutes and if we haven't then we send another
thankyou = "Thank you for your message, please provide as much information as you're comfortable sharing and we'll get back to you as soon as we can."

#  Disclaimer response is sent to ensure recipients don't send us things we can't, or aren't allowed to, deal with.
#
# In much the same way as we only send a Thank You every 30 mins or less, we only send the
# disclaimer once every 24 hours.
disclaimer = "DISCLAIMER: This is not an incident reporting service. If you believe you're being subjected to bullying, harassment, or misconduct then we cannot escalate on your behalf but we can advise you on your next steps."
